name: Deploy Static Site to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t yourdockerhubusername/static-site:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push yourdockerhubusername/static-site:${{ github.sha }}

  deploy_to_minikube:
    needs: build_and_push
    runs-on: self-hosted
    steps:
      - name: Set up Minikube Docker environment
        run: |
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression

      - name: Verify Docker configuration
        run: docker info

      - name: Pull Docker image from Docker Hub inside Minikube
        run: |
          docker pull yourdockerhubusername/static-site:${{ github.sha }}

      - name: Deploy the image to Minikube
        run: |
          kubectl create deployment static-site --image=yourdockerhubusername/static-site:${{ github.sha }}
          kubectl expose deployment static-site --type=LoadBalancer --port=80

      - name: Wait for deployment to complete
        run: |
          kubectl rollout status deployment/static-site
