jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Minikube
        run: |
          minikube start
          minikube status

      - name: Build Docker image
        run: |
          docker build -t static-site:latest .

      - name: Save Docker image as tarball
        run: docker save static-site:latest -o static-site.tar

      - name: Transfer Docker image to Minikube
        run: |
          minikube ssh "sudo docker load < static-site.tar"

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/static-site
