name: Deploy Static Website to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t static-site:latest .

      # Save Docker image as tarball
      - name: Save Docker image as tarball
        run: docker save static-site:latest -o static-site.tar

      # Transfer Docker image to Minikube
      - name: Transfer Docker image to Minikube
        run: |
          minikube ssh "sudo docker load < static-site.tar"
      
      # Deploy to Kubernetes
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Check status
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/static-site
